# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  k8s-yamls:
    description: "K8s yaml directory "
    required: true
    default: "K8s/deployment.yaml"
# outputs:
#   time: # id of output
#     description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
#  args:
#    - ${{ inputs.who-to-greet }}
