on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Mutate K8s deployment with Ocean Right-Sizing suggestions 
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ocean Right-Sizing local action 
        uses: ./ # Uses an action in the root directory
        id: local-ocean-right-sizing-mutator 
        env:
          SPOT_OCEAN_ID: ${{ secrets.OCEAN_ID }}
          SPOT_OCEAN_CONTROLLER: ${{ secrets.OCEAN_CONTROLLER }}
          SPOT_TOKEN: ${{ secrets.SPOT_TOKEN }}
          SPOT_ACCOUNT: ${{ secrets.SPOT_ACCOUNT }}
      - name: Ocean Right-Sizing remote action 
        uses: tsahiduek/ocean-right-sizing-githubaction@v0.1
        id: remote-ocean-right-sizing-mutator 
        env:
          SPOT_OCEAN_ID: ${{ secrets.OCEAN_ID }}
          SPOT_OCEAN_CONTROLLER: ${{ secrets.OCEAN_CONTROLLER }}
          SPOT_TOKEN: ${{ secrets.SPOT_TOKEN }}
          SPOT_ACCOUNT: ${{ secrets.SPOT_ACCOUNT }}
